name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/home-disconnect/
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v7.0.1
      - name: Set up Python
        uses: astral-sh/setup-uv@v10.1.0
        with:
          enable-cache: true
      - name: Build package
        run: uv run --with build -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.14.2
