name: Test

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true
      - uses: actions/setup-python@v7.0.0
      - run: |
          sudo pip install uv
          sudo uv run pytest
