name: Test

on: [pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - run: |
        sudo pip install uv
        sudo uv sync
    - run: |
        sudo uv run pytest tests/